// // Generated by ts-to-zod
// import { z } from "zod";

// export const periodSchema = z.object({
//   id: z.string(),
//   name: z.string(),
//   start: z.string(),
//   end: z.string(),
// });

// export const bellScheduleVariantSchema = z.object({
//   id: z.string(),
//   name: z.string(),
//   description: z.string().optional(),
//   isDefault: z.boolean().optional(),
//   recurrenceRuleSet: z.string(),
//   periods: z.array(periodSchema),
// });

// export const createPeriodInputSchema = periodSchema
//   .omit({ id: true })
//   .and(periodSchema.pick({ id: true }));

// export const bellScheduleSchema = z.object({
//   id: z.string(),
//   name: z.string(),
//   description: z.string().optional(),
//   variants: z.array(bellScheduleVariantSchema),
// });

// export const createBellScheduleVariantInputSchema = bellScheduleVariantSchema
//   .omit({ id: true })
//   .and(bellScheduleVariantSchema.pick({ id: true }))
//   .and(
//     z.object({
//       schedule_id: z.string(),
//       periods: z.array(createPeriodInputSchema),
//     }),
//   );

// export const createBellScheduleInputSchema = bellScheduleSchema
//   .omit({ id: true, variants: true })
//   .and(bellScheduleSchema.pick({ id: true }))
//   .and(
//     z.object({
//       variants: z
//         .array(createBellScheduleVariantInputSchema.omit({ schedule_id: true }))
//         .optional(),
//     }),
//   );
